### ISSUE TITLE
v5.0 Roadmap

### ISSUE THREAD

**Issue by yahiakr** [mongoosastic/mongoosastic#576]
# Mongoosastic v5.0 Roadmap

This work is currently happening in the [develop](https://github.com/mongoosastic/mongoosastic/tree/develop) branch.

- [x] Move to TypeScript.
- [x] Drop callback-style API, and make all the methods promise-based (using async/await syntax).
- [x] Migrate to JEST as a testing framework.
- [x] Migrate to the new version of Elasticsearch client library [@elastic/elasticsearch](https://github.com/elastic/elasticsearch-js).
- [ ] Update the documentation to explain the async/await syntax & the new options.
- [ ] Upgrade to Mongoose v6.
- [ ] Refactor `esTruncate` method: delete the index and recreate it with the same mapping.
- [ ] Open the option to pass an existing `esClient`.
- [ ] Update the example folder.
- [ ] Integrate github actions CI.

**Comment by yahiakr** [comment]
Ping @guumaster @meabed

**Comment by guumaster** [comment]
Welcome the two new maintainers @yahiakr and @meabed :tada:

**Comment by meabed** [comment]
Awesome - glad to contribute here, @yahiakr Thanks for great work, let know if you need support from with those items on the checklist, as well as if you could take a look at my code most of those items are done if this could help 🔥

**Comment by guumaster** [comment]
@meabed can you create a new PR with the parts that you already have from this list? Mention here which one would you work on, so it won't be duplicated

**Comment by yahiakr** [comment]
About `Jest`, the new `27.x` version does not support done callback and async test simultaneously (see this: [#10529](https://github.com/facebook/jest/issues/10529)).

As we are using both of them in event-based tests (e.g: to test `synchronize` method), and since Jest is a dev dependency, i think we can keep the current version for now, and focus on updating it after realising the 5.0 version.

**Comment by meabed** [comment]
I don't think we need jest, mocha is fine.

**Comment by guumaster** [comment]
@yahiakr I've notice that v26 runs ok, but v27 have some issues. It's ok to stick with v26. I'll remove it from the list.  @meabed, all tests are already in jest :)

**Comment by smolinari** [comment]
Is this still being worked on? I'm hugely interested in it. 

Scott

**Comment by guumaster** [comment]
@smolinari it's going slow but firm. I'll be released soon* 

(*) but with no promise on a specific date.

**Comment by smolinari** [comment]
> @smolinari it's going slow but firm. I'll be released soon*
> 
> (*) but with no promise on a specific date.

Awesome. That is the best answer I could get! 😁 

Scott

**Comment by HishamMubarak** [comment]
Looking forward to this release. I am not an expert, but if there is anything I could do to help, please point me in the right direction.

**Comment by GrapeoffJS** [comment]
I am really waiting for this release because of typescript, best wishes for all of mongoosastic team - you are the best!

**Comment by meabed** [comment]
> I am really waiting for this release because of typescript, best wishes for all of mongoosastic team - you are the best!
@GrapeoffJS I have released version here incase you are at hurry ( until this version is released ) https://github.com/meabed/mongoosastic-ts

**Comment by hnviradiya** [comment]
I am planning to support all (as they are small in numbers at moment) the pending issues with some freelancers working with me once this typescript version is released. Or you can also update me if you need any help with typescript upgrade as well. I will ask folks to work on that.

**Comment by guumaster** [comment]
If anyone want to help testing before release, you can install the first RC with the following command: 

`npm i mongoosastic@next` and you will get the latest rc, which is `v5.0.0-rc.1` at the moment. Thanks!

**Comment by Dreaming-Codes** [comment]
> If anyone want to help testing before release, you can install the first RC with the following command:
> 
> `npm i mongoosastic@next` and you will get the latest rc, which is `v5.0.0-rc.1` at the moment. Thanks!

It doesn't work for me, the package is not compiled and I have to open the node_modules folder by hand and run inside mongoosastic npm install && npm run build

**Comment by guumaster** [comment]
thanks @Dreaming-Codes it is already changed and built before publish. `rc.2` is available now.

**Comment by guumaster** [comment]
🚀  🎉  We have v5 live! cheers and thanks to @yahiakr and @meabed and all collaborators that made this possible!! 👏
